# Workflow to build and push Prod Web-Server

name: Build and Push - Prod

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'containers/web-server/frontend/**'
      - '.github/workflows/prod.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      VERSION_PROD: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.8.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Prod
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./containers/web-server/Dockerfile-prod
          push: true
          tags: ghcr.io/nismod/gri-web-server:${{ env.VERSION_PROD }}
          cache-from: type=registry,ref=ghcr.io/nismod/gri-web-server:buildcache
          cache-to: type=registry,ref=ghcr.io/nismod/gri-web-server:buildcache,mode=max

      - name: Update images on server and restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GRI_HOST }}
          username: ${{ secrets.GRI_USERNAME }}
          key: ${{ secrets.GRI_KEY }}
          port: 22
          script: |
            cd /opt/infra-risk
            docker compose -f docker-compose-prod.yaml pull web-server
            docker compose -f docker-compose-prod.yaml up -d webserver
